### ISSUE TITLE
2.0 errors exceptions apprearing in the console

### ISSUE THREAD

**Issue by dimateos** [R35007/data-size-count-vscode-extension#3]
Hey thanks for the extension!

I noticed many errors in the console, they seemed related to 2.0. 

I dont have a sample json with comments file but I'm posting the logs.
The issue seems to arise from how you treat paths (in windows?), maybe there could be exception control too?

<details><summary>Sample log</summary>

```js
[Extension Host] SyntaxError: Unexpected token '/', "/Users/die"... is not valid JSON
	at JSON.parse (<anonymous>)
	at t.DataSizeCount.getValidJSON (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169516)
	at t.DataSizeCount.getDataDetails (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2167439)
	at new t.DataSizeCount (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169132)
	at updateStatusBarItem (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2171530)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:164:21003)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.C (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:807)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:1023)
	at c.$acceptEditorPropertiesChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:34576)
	at E.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5980)
	at E.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5746)
	at E.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4778)
	at E.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3605)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:2297)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:8655)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6781)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
listWidget.ts:1004 [Extension Host] SyntaxError: Unexpected token ':', ":/Users/di"... is not valid JSON
	at JSON.parse (<anonymous>)
	at t.DataSizeCount.getValidJSON (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169516)
	at t.DataSizeCount.getDataDetails (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2167439)
	at new t.DataSizeCount (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169132)
	at updateStatusBarItem (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2171530)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:164:21003)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.C (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:807)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:1023)
	at c.$acceptEditorPropertiesChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:34576)
	at E.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5980)
	at E.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5746)
	at E.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4778)
	at E.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3605)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:2297)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:8655)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6781)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
listWidget.ts:1004 [Extension Host] SyntaxError: Unexpected token 'C', "C:/Users/d"... is not valid JSON
	at JSON.parse (<anonymous>)
	at t.DataSizeCount.getValidJSON (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169516)
	at t.DataSizeCount.getDataDetails (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2167439)
	at new t.DataSizeCount (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169132)
	at updateStatusBarItem (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2171530)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:164:21003)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.C (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:807)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:1023)
	at c.$acceptEditorPropertiesChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:34576)
	at E.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5980)
	at E.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5746)
	at E.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4778)
	at E.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3605)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:2297)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:8655)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6781)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
9listWidget.ts:1004 [Extension Host] SyntaxError: Unexpected non-whitespace character after JSON at position 3 (line 1 column 4)
	at JSON.parse (<anonymous>)
	at t.DataSizeCount.getValidJSON (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169516)
	at t.DataSizeCount.getDataDetails (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2167439)
	at new t.DataSizeCount (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2169132)
	at updateStatusBarItem (c:\Users\diego.mateos\.vscode\extensions\thinker.data-size-count-2.0.0\dist\extension.js:2:2171530)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:164:21003)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.C (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:807)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:1023)
	at c.$acceptEditorPropertiesChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:156:34576)
	at E.S (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5980)
	at E.Q (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:5746)
	at E.M (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:4778)
	at E.L (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:3605)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:151:2297)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at i.value (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:8655)
	at n.B (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:737)
	at n.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:954)
	at s.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:97:14453)
	at MessagePortMain.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:177:6781)
	at MessagePortMain.emit (node:events:519:28)
	at MessagePortMain._internalPort.emit (node:electron/js2c/utility_init:2:2285)
```
</details>

**Comment by R35007** [comment]
Hi @dimateos,

Removed the console logs from version [2.0.1](https://marketplace.visualstudio.com/items?itemName=Thinker.data-size-count).
